language: go

go:
  - "1.14"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"

before_install:
  - echo "current branch is ${BRANCH}"
  - if [ "${BRANCH}" == "master" ]; then travis_terminate 0; fi
  - ls ${BRANCH} && cd ${BRANCH}

stages:
  - name: Tests

jobs:
  include:
    - stage: "Tests"
      name: "go get"
      install: echo "skip"
      script: cd /tmp && go get "github.com/${TRAVIS_REPO_SLUG}/${BRANCH}@${BRANCH}"
      if: |
        (type = push AND branch != hw08) OR (type = pull_request AND head_branch != hw08) OR \
        (type = push AND branch != hw05) OR (type = pull_request AND head_branch != hw05) OR \
        (type = push AND branch != hw06) OR (type = pull_request AND head_branch != hw06) OR

    - stage: "Tests"
      name: "Makefile"
      install: go mod download
      script:
        - make install
        - make lint
        - make generate
        - make test
        - make build
        - make run
      if: |
        (type = push AND branch != hw08) OR (type = pull_request AND head_branch != hw08) OR \
        (type = push AND branch != hw05) OR (type = pull_request AND head_branch != hw05) OR \
        (type = push AND branch != hw06) OR (type = pull_request AND head_branch != hw06)
